when:
  - event: pull_request
    branch: master
    path:
      include: [ 'infrastructure/*' ]
      on_empty: true

steps:
  - name: terraform get plan
    image: ghcr.io/opentofu/opentofu:latest
    environment:
      TF_VAR_PM_AUTH_STRING:
        from_secret: TF_VAR_PM_AUTH_STRING
      TF_CLI_CONFIG_FILE: ./infrastructure/.tofurc
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - set -o pipefail
      - tofu -chdir=./infrastructure init 2>&1 | tee /woodpecker/tf_error.log
      - tofu -chdir=./infrastructure plan -input=false -out=tfplan
      - tofu show -no-color tfplan > plan.txt
      - |
        {
                  echo "### OpenTofu plan: $(grep -E '^(Plan:|No changes)' plan.txt || echo 'finished')"
                  echo
                  echo "<details><summary>Show plan</summary>"
                  echo
                  echo '```diff'
                  sed -E 's/^([[:space:]]+)([-+~])/\2\1/' plan.txt | head -c 60000
                  echo
                  echo '```'
                  echo "</details>"
                } > plan.md

  - name: Publish results
    image: ghcr.io/yyewolf/woodpecker-plugins/github-comment
    settings:
      github_token:
        from_secret: github_token
      comment_path: plan.md
      message_id: tofu_plan_message
      update_in_place: true